parameters:
    uploadDir: '%kernel.project_dir%/public/upload'
    exceptions:
        App\Exception\BookCategoryNotFoundException: { code: 404, hidden: false, loggable: false }
        App\Exception\SubscriberExistsException: { code: 409, hidden: false, loggable: false }
        App\Exception\RequestBodyConvertException: { code: 400, hidden: false, loggable: false }

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            bool $isDebug: '%kernel.debug%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ExceptionHandler\ExceptionMappingResolver:
        arguments: [ '%exceptions%' ]

    App\Listener\ApiExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }

    App\Listener\ValidationExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 16 }

    App\Service\UploadService:
        arguments: [ '@filesystem', '%uploadDir%' ]
