services:
    nginx:
        image: nginx:latest
        ports:
            - "81:80"
        volumes:
            - ./deploy/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

    database:
        container_name: postgres
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"

    app:
        build:
            dockerfile: ./deploy/php/Dockerfile
            target: "${BUILD_TARGET-app}"
        volumes:
            - ./:/var/www/html
            - ./deploy/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
        environment:
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
        extra_hosts:
            - host.docker.internal:host-gateway

